[2024-11-22 16:49:19,769 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E534B02120>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-11-22 16:49:23,402 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E534B029F0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-11-22 16:49:26,982 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E534B03350>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-11-22 16:49:30,545 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E534B022D0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-11-22 16:49:34,165 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E534B034A0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-11-22 16:49:37,788 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E534B03DD0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-11-22 16:49:41,414 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E534B247A0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-11-22 16:49:44,985 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E534B25160>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-11-22 16:49:48,534 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E534B03DA0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-11-22 16:49:52,125 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E534B01760>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-11-22 16:49:55,718 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E534B027B0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-11-22 16:49:59,280 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E534B03110>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-11-22 16:50:02,858 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E534B24C50>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-11-22 16:50:26,411 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001609CDA2330>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-11-22 16:50:29,985 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001609CDA2BD0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-11-22 16:50:33,602 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001609CDA3500>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-11-22 16:50:37,200 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001609CDA2540>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-11-22 16:50:52,590 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CB6D9F2330>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-11-22 16:50:56,125 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CB6D9F2B70>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-11-22 16:50:59,660 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CB6D9F34D0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-11-22 16:51:03,209 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CB6D9F16A0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-11-22 16:51:06,779 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CB6D9F3620>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-11-22 16:51:10,343 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CB6D9F3F80>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-11-22 16:51:13,881 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CB6DA10950>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
