[2024-12-05 11:29:56,709 >> ParserMessage.py] ERROR:  Error read Tag: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
[2024-12-05 11:29:56,781 >> ParserMessage.py] ERROR:  Error main cycle: list index out of range
[2024-12-05 11:31:06,176 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790922BA0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:31:09,976 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790923410>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:31:14,078 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001978DF616D0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:31:34,719 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790922900>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:31:49,930 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790923EC0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:31:54,309 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790940860>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:32:15,388 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000197909411F0>, 'Connection to 192.168.20.228 timed out. (connect timeout=None)'))
[2024-12-05 11:32:20,524 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790941B80>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:32:24,502 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790923DD0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:32:29,850 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790922E70>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:32:33,664 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000197909237A0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:32:37,510 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790941580>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:32:41,300 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790940C20>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:32:45,829 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000197909401D0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:32:49,700 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000197909239E0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:32:53,579 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790922D20>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:32:58,010 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790923EC0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:33:02,075 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000197909404A0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:33:22,645 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790940FE0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:33:43,706 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000019790941A60>, 'Connection to 192.168.20.228 timed out. (connect timeout=None)'))
[2024-12-05 11:33:58,825 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790921E20>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:34:03,331 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000197909230B0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:34:07,622 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790923170>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:34:11,410 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790941D60>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:34:15,942 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790940D40>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:34:20,014 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000197909405F0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:34:24,114 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790923A40>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:34:28,940 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790923AA0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:34:32,912 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790922A50>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:34:37,008 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000197909407D0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:34:41,420 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790941490>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:34:45,502 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790941B20>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:34:50,007 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790922360>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:34:54,232 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790923740>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:34:58,306 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000197909423F0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:35:02,312 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790940F20>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:35:06,623 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000197909401A0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:35:10,707 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790942720>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:35:14,805 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790923B30>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:35:19,320 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790922FC0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:35:23,404 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790940860>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:35:27,494 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790940D40>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:35:31,814 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000197909409B0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:35:36,105 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790943050>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:35:40,189 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000197909233B0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:35:44,361 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000197909214C0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:35:48,806 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790940800>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:35:52,887 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790941490>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:35:56,893 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790942840>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:36:01,293 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000197909426C0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:36:05,398 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790923770>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:36:09,486 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790921D90>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:36:13,683 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790940CB0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:36:17,777 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790940C80>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:36:22,804 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790921730>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:36:27,001 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790923800>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:36:31,084 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790923F50>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:36:36,419 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790921F40>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:36:40,509 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790923710>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:36:44,611 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000197909423F0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:36:48,697 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790941220>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:36:52,801 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790940170>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:36:57,398 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790921C70>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:37:01,501 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790920C50>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:37:05,716 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790940620>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:37:09,798 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000197909413A0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:37:24,869 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790941CA0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:37:32,958 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790942FF0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:37:36,727 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790921D90>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:37:40,723 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790922720>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:37:51,488 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790941E50>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:37:55,829 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019790941190>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:54:00,294 >> ParserMessage.py] ERROR:  Error read Tag: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
[2024-12-05 11:54:00,309 >> ParserMessage.py] ERROR:  Error main cycle: list index out of range
[2024-12-05 11:54:04,813 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A2128A32F0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:54:08,991 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A2128A3BF0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:54:12,996 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A2128A29F0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:54:17,104 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A2128A3DA0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:54:21,387 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A2128C06B0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:54:25,273 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A2128C0FB0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:54:29,230 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A2128C18E0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:54:33,783 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A2128A0DD0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:54:37,872 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A2128A2C60>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:54:41,960 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A2128A38C0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:54:46,178 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A2128C1730>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:54:50,349 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A2128C0C50>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:54:54,352 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A2128C0170>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:54:58,570 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A2128A27B0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:55:02,661 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A2128A2FC0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:55:06,862 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A2128A0B30>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:55:10,966 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A2128C0230>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:55:15,154 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A2128C0E00>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:55:19,255 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A2128C17F0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:55:23,254 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A2128A3F80>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:55:27,451 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A2128A0AD0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:55:31,419 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A2128A2E10>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:55:36,463 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A2128C0A70>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:55:40,556 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A2128C06B0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:55:44,631 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A2128C0050>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:55:53,654 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A2128A3B90>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:55:57,747 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A2128A2720>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:56:02,082 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A2128A0AA0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:56:06,253 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A2128C1040>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:56:10,358 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A2128C2030>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:56:19,375 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A2128C2930>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:56:23,566 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A2128A0B60>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:56:28,058 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A2128A3770>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:56:32,152 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A2124C31D0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:56:36,240 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A2128C0C80>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:56:40,759 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A2128C0BC0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:56:44,850 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A2128C3200>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:56:48,940 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A2128A2E10>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:56:53,435 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A2128A2AE0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:56:57,438 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A2128A3950>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:57:01,424 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A2128C0FE0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:57:05,937 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A2128C2420>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:57:09,951 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A2128C3B30>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:57:14,041 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A2128A3EF0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2024-12-05 11:57:31,649 >> ParserMessage.py] ERROR:  Error send output json: HTTPConnectionPool(host='192.168.20.228', port=5200): Max retries exceeded with url: /messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A2128A3A70>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
